CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS journal_entries (
  id SERIAL PRIMARY KEY,
  entry TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  embedding VECTOR(1536)
);
